### ISSUE TITLE
Search not working unless I comment out try block

### ISSUE THREAD

**Issue by jedverity** [xolox/vim-notes#53] opened 2013-12-18 02:38 UTC
Every search I performed would show that it was searching keyword index (0.23.4), but it would just go away errorlessly after a few seconds yielding no results, even when searching for tags or other keywords that I could see existed in the index.pickle and tags.txt files.

Commenting out the try block in autoload/xolox/notes.vim#search solved the problem, however. Surely it's not a good idea to keep it this way. How can I assist in the resolution of this?

Awesome plugin otherwise!

**Comment by AmaruCoder** [comment] 2015-02-24 06:11
I am having the same problem. Running OSX Yosemite, with VIM 7.4. I have installed vim-shell as suggested above, and the search works, but only with tags; every other search is unreliable. By the way, thank you for the plugin, it is allowing me to implement zettelkasten in VIM.

**Comment by mattymil** [comment] 2015-07-28 12:11
Having the same problem here running OS X Yosemite. I have installed VIm-Shell, as per other commenters and still no luck. However if I search via regexp it returns expected results.

**Comment by cahartm** [comment] 2015-08-31 16:53
Having same issue in Win7, known existing text string existing in several files.  I have also manually installed vim-shell, but search still not working for me.  Thanks for a fantastic plug-in!

**Before installing vim-shell:**

notes.vim 0.31.1: Searching notes using keyword index ..
notes.vim 0.31.1: Executing external command python "c:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\search-notes.py" "--database" "c:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\index.pickle" "--ignore-case" "--notes" "X:\notes" "tystad"
not found in 'runtimepath': "autoload/xolox/shell.vim"
vim-misc 1.17.1: Executing external command using system() function: python "c:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\search-notes.py" "--database" "c:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\index.pickle" "--ignore-case" "--notes" "X:\notes" "tystad"
notes.vim 0.31.1: Search script output (raw): ['Found 27 notes in X:\notes ..', 'Python works fine!', 'X:\notes\Ethernet Phase 1B.md', 'X:\notes\eWFM.md']
notes.vim 0.31.1: Search script returned invalid output :-(
notes.vim 0.31.1: Populating quick-fix window using command: vimgrep /\_^\_.*tystad/j X:\notes\amo-rfa-legacy-bpms.md X:\notes\cybd-irthnet-gis-fiber.md X:\notes\EMEA-Offnet-Jennifer.md X:\notes\EMEA-VC-Albert.md X:\notes\ESRI-Portal.md X:\notes\Ethernet\ Phase\ 1B.md X:\notes\eWFM.md X:\notes\FederatedInventory.md X:\notes\FieldRequired-GCR-Steve-Leveck.md X:\notes\FirstTestNote.md X:\notes\GFS-Region-Division-Market-GIS-pointInPoly.md X:\notes\GLM-OperationalMarket-OpsServingMarket.md X:\notes\Globalization.md X:\notes\GTMI.md X:\notes\MINTj-Diego.md X:\notes\NC\ Automated\ Test.md X:\notes\PitneyBowes-UK.md X:\notes\RowPhase2.md X:\notes\SchedulerHandoff.md X:\notes\SecondTestNote.md X:\notes\SEO-MetaStorm.md X:\notes\spatialAnalyst-Fendry.md X:\notes\Tibco-OE-Pipeline-getCustomerOrder.md X:\notes\Transport-Enhancements-Donna.md X:\notes\TW-ramp-Roman.md X:\notes\VoiceAutoAssignOrders.md X:\notes\WorkVu.md
notes.vim 0.31.1: Populated quick-fix window in 0.0046 seconds.
notes.vim 0.31.1: No matches
notes.vim 0.31.1: Searched notes in 0.77 seconds.


**After vim-shell installed:**

notes.vim 0.31.1: Searching notes using keyword index ..
notes.vim 0.31.1: Executing external command python "C:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\search-notes.py" "--database" "C:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\index.pickle" "--ignore-case" "--notes" "X:\notes" "tystad"
shell.vim 0.13.6: Checking if compiled DDL is supported ..
shell.vim 0.13.6: Looks like the DDL is not working! (Vim raised an exception: Vim(let):E364: Library call failed for "libversion()")
vim-misc 1.17.1: Executing external command using system() function: python "C:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\search-notes.py" "--database" "C:\cygwin64\home\me\\.vim_runtime\sources_non_forked\vim-notes\misc\notes\index.pickle" "--ignore-case" "--notes" "X:\notes" "tystad"
notes.vim 0.31.1: Search script output (raw): ['Found 27 notes in X:\notes ..', 'Python works fine!', 'X:\notes\Ethernet Phase 1B.md', 'X:\notes\eWFM.md']
notes.vim 0.31.1: Search script returned invalid output :-(
notes.vim 0.31.1: Populating quick-fix window using command: vimgrep /\_^\_.*tystad/j X:\notes\amo-rfa-legacy-bpms.md X:\notes\cybd-irthnet-gis-fiber.md X:\notes\EMEA-Offnet-Jennifer.md X:\notes\EMEA-VC-Albert.md X:\notes\ESRI-Portal.md X:\notes\Ethernet\ Phase\ 1B.md X:\notes\eWFM.md X:\notes\FederatedInventory.md X:\notes\FieldRequired-GCR-Steve-Leveck.md X:\notes\FirstTestNote.md X:\notes\GFS-Region-Division-Market-GIS-pointInPoly.md X:\notes\GLM-OperationalMarket-OpsServingMarket.md X:\notes\Globalization.md X:\notes\GTMI.md X:\notes\MINTj-Diego.md X:\notes\NC\ Automated\ Test.md X:\notes\PitneyBowes-UK.md X:\notes\RowPhase2.md X:\notes\SchedulerHandoff.md X:\notes\SecondTestNote.md X:\notes\SEO-MetaStorm.md X:\notes\spatialAnalyst-Fendry.md X:\notes\Tibco-OE-Pipeline-getCustomerOrder.md X:\notes\Transport-Enhancements-Donna.md X:\notes\TW-ramp-Roman.md X:\notes\VoiceAutoAssignOrders.md X:\notes\WorkVu.md
notes.vim 0.31.1: Populated quick-fix window in 0.0034 seconds.
notes.vim 0.31.1: No matches
notes.vim 0.31.1: Searched notes in 0.69 seconds.

**Comment by xolox** [comment] 2015-11-01 11:55
The output that @cahartm quoted shows a different issue then previously discussed here. I'm specifically referring to the following line in the output:

```
notes.vim 0.31.1: Search script output (raw): ['Found 27 notes in X:\notes ..', 'Python works fine!', 'X:\notes\Ethernet Phase 1B.md', 'X:\notes\eWFM.md']
```

The "Found 27 notes ..." message is not supposed to be there; it's printed on standard error and shouldn't be captured as standard output. Not sure whether Windows, Vim or Cygwin is to blame there but I think I just fixed that issue, so the latest version of vim-notes should work for @cahartm unless he's also affected by the other bug discussed here...

**Comment by xolox** [comment] 2015-11-01 14:13
The good news is that I'm able to reproduce this issue now. The bad news is that Vim and I have been butting heads for the better part of my afternoon now and I'm not winning :-(. I'm absolutely flabbergasted by the behavior I'm seeing:

- The Python script (correctly) reports several matching files (nothing wrong there, this part works whether vim-shell is installed or not).
- The matched filenames are given to `:vimgrep` in order to populate the quick-fix list.
- The `:vimgrep` command (logged when you do `:verbose SearchNotes ...`) reports no errors but also doesn't populate the quick-fix list.
- When I literally just copy/paste the logged `:vimgrep` command and execute it, then it correctly populates the quick-fix list! ಠ_ಠ
- Of course I tried to strip the code surrounding the `:vimgrep` call down to the bare minimum (e.g. removing the swap hack and `&eventignore` stuff) but that didn't change anything in the observed behavior.
* As previously implied in the discussion here Vim's `try` / `catch` / `finally` seems to have some weird interaction in all of this, however then I would expect the `:vimgrep` command to report an error, but it doesn't do that, it's just completely silent and the commands after it are also executed (so program flow doesn't change).

I've tried adding *a lot more logging* in my local checkout and gradually raising the `&verbose` option just before the call to `:vimgrep` is made (I ended up with `&verbose` set to 15) to see what the hell is going on inside Vim, but even that doesn't help to clarify anything. As expected some automatic commands trigger but I don't see how those would influence the functionality of `:vimgrep`.

```
notes.vim 0.33.2: Performing keyword search (booyah) ..
notes.vim 0.33.2: Searching notes using keyword index ..
notes.vim 0.33.2: Executing external command python2 '/home/peter/projects/vim/notes/misc/notes/search-notes.py' '--database' '~/.local/vim/notes/index.pickle' '--ignore-case' '--notes' '/home/peter/projects/dotfiles/docs/notes' 'booyah'
not found in 'runtimepath': "autoload/xolox/shell.vim"
vim-misc 1.17.6: Generated shell expression: (python2 '/home/peter/projects/vim/notes/misc/notes/search-notes.py' '--database' '~/.local/vim/notes/index.pickle' '--ignore-case' '--notes' '/home/peter/projects/dotfiles/docs/notes' 'booyah') 1>'/tmp/vWAWNVr/10' 2>'/tmp/vWAWNVr/11'
vim-misc 1.17.6: Executing external command using system() function: sh -c '(python2 '\''/home/peter/projects/vim/notes/misc/notes/search-notes.py'\'' '\''--database'\'' '\''~/.local/vim/notes/index.pickle'\'' '\''--ignore-case'\'' '\''--notes'\'' '\''/home/peter/projects/dotfiles/docs/notes'\'' '\''booyah'\'') 1>'\''/tmp/vWAWNVr/10'\'' 2>'\''/tmp/vWAWNVr/11'\'''
notes.vim 0.33.2: Search script output (raw): ['Python works fine!', '/home/peter/projects/dotfiles/docs/notes/2014-04-03']
notes.vim 0.33.2: Search script output (processed): ['/home/peter/projects/dotfiles/docs/notes/2014-04-03']
notes.vim 0.33.2: Search script reported 1 matching note.
notes.vim 0.33.2: Skipping phase 1 search (performed using Python script) ..
notes.vim 0.33.2: Performing phase 2 search to populate quick-fix window ..
notes.vim 0.33.2: Populating quick-fix window using command: vimgrep /\cbooyah/j /home/peter/projects/dotfiles/docs/notes/2014-04-03
line 15: vimgrep /\cbooyah/j /home/peter/projects/dotfiles/docs/notes/2014-04-03
Executing QuickFixCmdPre Auto commands for "*vimgrep*"
autocommand let g:startify_locked = 1
line 0: let g:startify_locked = 1
Executing QuickFixCmdPre Auto commands for "*vimgrep*"
autocommand call xolox#easytags#disable_automatic_updates()
line 0: call xolox#easytags#disable_automatic_updates()
calling function xolox#easytags#disable_automatic_updates
line 1:   let s:easytags_auto_update_save = xolox#misc#option#get('easytags_auto_update', 1)
calling function xolox#easytags#disable_automatic_updates..xolox#misc#option#get
line 1:   " Expects one or two arguments: 1. The name of a variable and 2. the default
line 2:   " value if the variable does not exist.
line 4:   " Returns the value of the variable from a buffer local variable, global
line 5:   " variable or the default value, depending on which is defined.
line 7:   " This is used by some of my Vim plug-ins for option handling, so that users
line 8:   " can customize options for specific buffers.
line 9:   if exists('b:' . a:name)
line 12:   elseif exists('g:' . a:name)
line 15:   elseif exists('a:1')
function xolox#easytags#disable_automatic_updates..xolox#misc#option#get returning #1
continuing in function xolox#easytags#disable_automatic_updates
line 2:   let g:easytags_auto_update = 0
function xolox#easytags#disable_automatic_updates returning #0
continuing in QuickFixCmdPre Auto commands for "*vimgrep*"
line 16:     let &verbose = vbs_save
notes.vim 0.33.2: Populated quick-fix window in 0.058 seconds.
notes.vim 0.33.2: Encountered error during search: No matches found or :vimgrep command failed to populate the quick-fix list! (function xolox#notes#search..<SNR>61_internal_search..<SNR>61_vimgrep_wrapper, line 20)
```

As can be seen in the log above I tried prefixing the pattern given to `:vimgrep` with `\c` but that also doesn't change the results. The last line shows an error that is not normally reported, I added it in my local checkout for instant feedback when `:vimgrep` behaves in an unexpected way.

**Comment by xolox** [comment] 2015-11-01 14:19
I just committed and released 08b974712b5ea97e3dba0dc81c4560da794eab80 which at the very least recognizes the buggy situation and alerts the user about it instead of keeping silent and provoking frustration all around. At this point I'm gravitating between two expectations:

- This might be a really stupid and trivial bug that, once found, provokes a huge face palm on my side.
- The alternative is a really tricky interaction between Vim plug-ins and Vim (script) internals.

The new version indeed consistently reports the new error when performing a keyword search without vim-shell installed and consistently doesn't report the error (i.e. works fine) when vim-shell is installed.

The thing that I don't understand is that the Python script works fine in either case, and this is the only part which has interaction with vim-shell.

So either the mere presence of vim-shell changes global state which hides the bug, or the detection of whether vim-shell is installed somehow causes these obscure problems?

**Closed** 2015-11-04 18:38 UTC

**Comment by xolox** [comment] 2015-11-04 18:44
Okay I'm sick of fighting obscure Vim script 'features' so have now decided to go with the flow, remove the try/catch construct, forget this issue ever happened and get on with my life (doing more productive things than fighting obscure corners of Vim [script] for hours on end ;-).

Thanks for the copious amounts of feedback on this issue and sorry for dragging this out for so long, I usually try to understand what I'm doing, even if that takes a lot of time (because one can usually learn from obscure bugs like these).

In my testing `:SearchNotes` now works fine with and without vim-shell installed, so I'm assuming this issue is indeed resolved. If not then feel free to reopen this issue or create a new one.

Happy Vimming all!

**Comment by kimsin98** [comment] 2016-06-18 04:57
`:SearchNotes` works fine without vim-shell, but trying to use `:RelatedNotes` results in an alert about this issue.
